### ISSUE TITLE
Concatenating multiple archives

### ISSUE THREAD

**Issue by jamespinkerton** [google/tensorstore#102]
Hi. I'm using this project and it's working extremely well for me.

I have a setup where every day I take data from that day and store it with tensorstore. It's important for reliability reasons that each day's process be independent of the other days, so I don't want to modify past archives.

My application is that I download multiple days' data and analyze them together. I think about days as an extra dimension.

Is there a way to stack multiple existing tensorstore archives that all have the same dimension when reading so that the library can handle the multiprocessing etc instead of the user?

Thanks so much!

**Comment by jbms** [comment]
Yes, you can do that with the `stack` driver:

https://google.github.io/tensorstore/driver/stack/index.html

This driver allows you to do the equivalent of `np.stack`, `np.concatenate`, `np.block`, and also more generally to overlay arrays on top of each other.

Unfortunately, we don't yet have a convenient C++ or Python API for creating a stack driver-backed TensorStore object that corresponds to those various NumPy APIs --- instead you will have to create the JSON spec yourself.

**Comment by jamespinkerton** [comment]
This is very helpful. I think it's exactly what I wanted. I do have a follow-up question that I'm struggling with (it's maybe more generic than just tensorstore). I have a snipped of code that reindexes each element. I'm not sure if it's possible to combine this kind of reindexing with tensorstore stack. The reason I don't know what to do is that I'm reindexing both on the out and in the oindex at the same time. Is it easy to translate this into stack?

```
def select_tensorstore(
    urls: list[str],
    start_ixs_list: list[list[str]],
    end_ixs: list[str],
) -> np.ndarray:
    r = []
    for url, start_ixs in zip(urls, start_ixs_list):
        ts_spec = {
            "driver": "zarr",
            "kvstore": url,
        }
        z1 = tensorstore.open(ts_spec, create=False, read=True).result()
        out_ix = [
            i for i, key in enumerate(end_ixs) if key in set(start_ixs)
        ]
        in_ix = [
            i for i, key in enumerate(start_ixs) if key in set(end_ixs)
        ]
        input_shape = z1.shape
        output_samples = input_shape[0]
        assert output_samples.is_integer()
        output_shape = (
            int(output_samples),
            len(end_ixs),
        )
        out = np.zeros(output_shape, dtype=np.float32)
        out[:, out_ix] = z1.oindex[:, in_ix]
        r.append(out)
    return np.concatenate(r, axis=0)
```

**Comment by jbms** [comment]
`stack` can definitely do the equivalent of the outer `concatenate`, and serves that purpose well.

The `out[:, out_ix] = ...` is basically a scatter operation.  TensorStore doesn't specifically support a "virtual scatter" operation, but it could be done with the stack driver.  However, that would require `k` stack layers, where `k` is the number of contiguous components within `out_ix`, or for simplicity, `len(out_ix)` stack layers.  Depending on the size in the other dimensions, this might have too much overhead, though it may also work fine.

If, instead of 0, it would be okay to substitute an arbitrary value at `out[:, j]` for values of `j` not in `out_ix`, then you could instead invert `out_ix` (substituting e.g. an index of 0 for missing positions) and then just use regular indexing rather than this scatter operation.

Another way to accomplish this with tensorstore is to use the `virtual_chunked` adapter.   That creates a tensorstore from an arbitrary Python function.  You could use `virtual_chunked` with the code from within your loop, and then apply the `stack` driver to concatenate the `virtual_chunked` drivers.

**Comment by jamespinkerton** [comment]
I think your solution 1 would have a lot of overhead and would create a lot of issues. Solutions 2 and 3 seem like the best candidates.

For solution 2, I think I could pad the last index of every archive with 0s and then it would be simple. I just have to duplicate that last index over and over again in my in_ix, right? I’m not sure if there’s an easier way to insert it without padding the original upload.

**Comment by jbms** [comment]
You could actually use the stack driver to pad with zeros virtually, by combining the original array with an array of zeros.

Then you can do the indexing on top of that, and then use the stack driver again to concatenate.

**Comment by jamespinkerton** [comment]
OK I'm very close to having a solution. The last issue is the lack of a python API for the stack driver. If there a way for me to take the other parts of the API using python and then extract the JSON from that and re-compose it for stack?

**Comment by jbms** [comment]
Adding a Python API for the stack driver is on the TODO list.

You can just call `store.spec().to_json()` to get the JSON representation.

**Comment by jamespinkerton** [comment]
OK I got this working. Thanks for your help!
