### ISSUE TITLE
Add support for zarrv2 dimension_names and dimension_units

### ISSUE THREAD

**Issue by blasscoc** [google/tensorstore#121]
The Zarr v2 driver does not provide a way to assign dimension units to the store. But it would be awesome if it did. The Zarr v2 spec https://zarr.readthedocs.io/en/stable/spec/v2.html does allow for "attributes" in the .zattrs file, perhaps that's a way to enable saving them.

FWIW I did make an effort to understand the driver, but it got a bit heavy. I'm more than happy to try again if you would give some guidance how one might make this change (if it's reasonable).

  EXPECT_THAT(
      tensorstore::Open(
          {{"driver", "zarr"}, {"kvstore", {{"driver", "memory"}}}},
          tensorstore::OpenMode::create, dtype_v<uint8_t>, Schema::Shape({1}),
          Schema::DimensionUnits({"nm"}))
          .result(),
      MatchesStatus(absl::StatusCode::kInvalidArgument,
                    ".*: Dimension units not supported by zarr driver"));

**Comment by jbms** [comment]
This is not yet supported for zarr v2 (similar to the lack of support for dimension names) because the attributes are stored in a separate file, which poses some challenges for the existing implementation, in part related to the fact that it would not be possible to atomically write both the .zarray and .zattrs files together on kvstores that support only single-file atomic operations.

In case you are able to use it, note that the zarr v3 driver does support `dimension_units`.

**Comment by blasscoc** [comment]
Hi jbms,

Thanks for the reply. 

I did spent a little more time to understand more the code, and that makes sense. You even made a comment here explaining that, https://github.com/google/tensorstore/blob/master/tensorstore/driver/kvs_backed_chunk_driver.h

/// \file Framework for implementing TensorStore drivers for storage formats
/// like zarr, n5, and Neuroglancer precomputed backed by an arbitrary key-value
/// store, where there is a key-value store entry for metadata (which may be
/// shared by multiple independent arrays) and one key-value store entry per
/// chunk.

I have used the Zarrv3 driver and it's really great, kudos on implementing the latest Zarr we're really excited to start using that.

Thanks
Ben
