### ISSUE TITLE
TransformedArray Materialize - provide a writable SharedArray

### ISSUE THREAD

**Issue by blasscoc-tgs** [google/tensorstore#124]
Hi Tensorstore,

Is it possible to have a Materialize method that returns a SharedArray, or View that is writable?

Right now the return type of Materialize is const.

index_space/transformed_array.h - line 443
Result<SharedArray<const Element, Rank, OriginKind>> Materialize

The use case would be to transform an array and be able to take advantage of transformed indexing to modify the values, without having to make a copy of the array using MakeCopy.

Currently we are only able to read from the result created by Materialize.

**Comment by jbms** [comment]
This API could potentially use some improvements.  If the source array element type is non-const, it would certainly be valid for the returned array to have a non-const element type.  However, the issue is that the returned array may either reference the existing array or be newly allocated, depending on the type of transformation and the options specified.  Therefore, it may be confusing if you mutate the returned array since that may or may not affect the original array.  It is for that reason that the returned array currently has a const element type in all cases.

An alternative is to use an operation like `CopyTransformedArray` in conjunction with indexing operations applied to the source and/or target arrays.

Another alternative is to use `tensorstore::FromArray` (see tensorstore/driver/array/array.h) to create a TensorStore object that references an existing array.  Any writes to this TensorStore, including with indexing operations, will modify the original array.

**Comment by blasscoc-tgs** [comment]
That makes sense, thanks for the help.
