### ISSUE TITLE
Slow random read performance

### ISSUE THREAD

**Issue by muchanem** [google/tensorstore#178]
I have a dataset created as follows:
```python 
dataset = ts.open(
    {
    'driver': 'zarr3',
    'kvstore': {
        'driver': 'file',
        'path': '/net/projects/interp/ts_acts',
        },
    },
    dtype=ts.float32,
    chunk_layout=ts.ChunkLayout(
    read_chunk_shape=[1, 1, 3072],
    write_chunk_shape=[2560, 256, 3072],
    ),
    shape=[3919360, 256, 3072],
).result()
```

When I read into it with random slicing as such
```python
from random import shuffle
idxs = list(product(list(range(2304000)),list(range(256))))
shuffle(idxs)
to_load = idxs[0:409600]
outer, inner = list(zip(*to_load))
out = dataset[outer,inner].read().result()
```

Read performance is quite bad (~10MB/s on average). Is there a better chunking to optimize performance (or a better data shape, e.g. storing as [3919360*256,3072] and only slicing across one dimension) or something else I could do to achieve performance uplift? It seems that even contiguous slicing has pretty bad performance (which does make sense with the extremely small shards). Interestingly, in both cases occasionally read performance will jump into the 100s of MB/s 

P.S. I don't strictly need random access, rather I am trying to minimize reading from the same place in the first dimension (i.e. to the extent possible [0,0,:] and [0,0,:] should not be in the same batch)

**Comment by jbms** [comment]
Is "/net" a network filesystem?  If your filesystem has high latency you may get better performance by increasing `file_io_concurrency` --- e.g. add `'kvstore': { 'driver': 'file', 'file_io_concurrency': {'limit': 1024}, 'path': '...'}`

**Comment by muchanem** [comment]
This has helped somewhat, thank you! Got a performance uplift to 20MB/s, are there any other optimizations or should I look to a different sharding layout?

**Comment by jbms** [comment]
To be clear, you basically want to randomly over the first two dimensions, but always read the full 3072 elements?

**Comment by muchanem** [comment]
Yes!

**Comment by muchanem** [comment]
Only been able to get up to ~20MB/s read performance unfortunately. Would writing the tensorstore as rank 2 instead of rank 3 so iteration only happens over one dimension improve performance or will only using a bigger sub-chunk/shard size help?

**Comment by jbms** [comment]
Rank 2 vs rank 3 won't help.

There are a few issues:

 - With your random sampling, any given batch is likely to hit every shard.  With 1531 shards, and each shard index being 10MB, you will actually need the cache to be larger than 15GB in order to keep all of the shard indices cached.  Otherwise, you will have to read 15GB of shard index data for every batch, and if the size of the batch is not significantly larger than 15GB, there will be a high level of read amplification.  For this type of use case, we might need to introduce a different sharded format to avoid needing to consume so much memory caching the shard index.
 - Assuming you sort out the shard index caching, you will still need to get high throughput from random 12KB reads.  Assuming your network filesystem can accommodate the desired throughput, you will need to set the number of concurrent requests high enough according to the latency.  For example if each 12KB random read from the network filesystem has a latency of 10ms, then you will need at least 833 concurrent requests to achieve a throughput of 1GB/s.  If the latency is 100ms, then you will 8330 concurrent requests.

**Comment by muchanem** [comment]
Thanks for all the help here! Was able to improve speeds in a non-network mounted setting but the way our HPC network mounting works makes it ~impossible for reads with small block size to be fast

**Comment by laramiel** [comment]
When poking at the other bug, my smaller benchmark shows the essential problem: No cache hits.

```
/tensorstore/cache/chunk_cache/reads:       817515
/tensorstore/cache/evict_count:             820956
/tensorstore/cache/hit_count:               6
/tensorstore/cache/kvs_cache_read{changed}: 822110
/tensorstore/cache/miss_count:              826697

/tensorstore/kvstore/file/list:        1
/tensorstore/kvstore/file/open_read:   7657
/tensorstore/kvstore/file/read:        822110
/tensorstore/kvstore/file/batch_read:  818766
/tensorstore/kvstore/file/bytes_read:  14861753170
```
