### ISSUE TITLE
ValueError when using an array to index

### ISSUE THREAD

**Issue by perlman** [google/tensorstore#18]
I've been trying to diagnose an issue where I get a ValueError exception when using an index array. This happens _very_ infrequently, but I am now able to reproduce it in the context of a specific input within a larger application.

Unfortunately, my efforts to demonstrate the bug with a snippet have been unsuccessful, but I'll update this issue if I can.

Given a numpy array `co` of `shape=(1044, 3)` and `dtype=int32`:
```
# This works
for row in range(co.shape[0]):
    x = vol[co[row, 0], co[row, 1], co[row, 2]].read().result()

# This also works
split = co.shape[0] // 2
x1 = vol[co[:split, 0], co[:split, 1], co[:split, 2]].read().result()
x2 = vol[co[split:, 0], co[split:, 1], co[split:, 2]].read().result()

# But this doesn't
co_id = vol[co[:, 0], co[:, 1], co[:, 2]].read().result()
```

The exception I get is:
```
  File "./app/process.py", line 39, in _get_ids
    co_id = vol[co[:, 0], co[:, 1], co[:, 2]].read().result()
ValueError: In index array map for output dimension 0: Index 28 is outside valid range [28928, 29056)
```

The error is confusing for two reasons. First, all of the values are within this range:

```
print(co[28])
print('0: ', np.min(co[:,0]), np.max(co[:,0]))
print('1: ', np.min(co[:,1]), np.max(co[:,1]))
print('2: ', np.min(co[:,2]), np.max(co[:,2]))

[28931 12703  3603]
0:  28928 29054
1:  12672 12777
2:  3586 3647
```

Secondly, the actual volume is _much_ larger:

```
TensorStore({
  'context': {'cache_pool': {'total_bytes_limit': 200000000}},
  'driver': 'zarr',
  'dtype': 'int16',
  'key_encoding': '/',
  'kvstore': {
    'driver': 'file',
    'path': '/data/fields/flywire_v1/field.zarr/s2',
  },
  'metadata': {
    'chunks': [128, 128, 128, 2],
    'compressor': {'clevel': 9, 'cname': 'zstd', 'id': 'blosc', 'shuffle': 1},
    'dtype': '<i2',
    'fill_value': 0,
    'filters': None,
    'order': 'C',
    'shape': [63488, 36864, 7062, 2],
    'zarr_format': 2,
  },
  'recheck_cached_data': 'open',
  'transform': {
    'input_exclusive_max': [[67584], [36864], [7063], [2]],
    'input_inclusive_min': [4096, 0, 1, 0],
    'output': [
      {'input_dimension': 0, 'offset': -4096},
      {'input_dimension': 1},
      {'input_dimension': 2, 'offset': -1},
      {'input_dimension': 3},
    ],
  },
})
```

**Comment by jbms** [comment]
Thanks for reporting this.  I will have to look into this --- certainly if you are able to provide me a way to reproduce, that would help. 

I can explain the meaning of the error, at least: the error is not referring to co[28], it is just indicating that the index array contains the value 28, which is outside the valid range [28928, 29056).  The way it works is that when you slice a TensorStore object like `vol[co[:, 0], co[:, 1], co[:, 2]]`, you end up creating an IndexTransform that holds the index arrays. Tensorstore does not validate index arrays immediately, instead it validates them only when necessary (because the correct bounds are not necessarily known when the TensorStore is created).  But the IndexTransform keeps track of the relevant bounds that apply to the index values, initially the full bounds of the volume.  The range [28928, 29056) that you see in the error message is a result of the way the grid partitioning works: for a chunked format like zarr, tensorstore performs the read by partitioning the full index transform for the read request by the grid, such that it ends up with a separate index transform for each grid cell.  Each of those separate index transforms is used to copy data from the decoded chunk into the output array, and that copy process validates the index values against the bounds of the individual chunk.  However, the partitioning should have already ensured that an index of 28 would not end up in a chunk for the range [28928, 29056).  The fact that it occurred suggests some sort of memory corruption bug in tensorstore.  You can check if your `co` index array even contained 28 in the first place --- if it does not, that would be even more indication of memory corruption.

Normally when debugging an issue like this I would attempt to reproduce with the python extension compiled with AddressSanitizer.  I haven't attempted to do that with the open source tensorstore build yet, though.  It seems like in principle it should be possible, though: https://stackoverflow.com/questions/55692357/address-sanitizer-on-a-python-extension

**Comment by jbms** [comment]
If you can say more about the conditions within your application that you are able to reproduce it, that may be helpful as well.  E.g. if you break in pdb right when the error occurs, and you repeat with the same `co` array, does the error occur?

**Comment by perlman** [comment]
It's a web service, and by the time the code gets to this line the input values have been spatially binned and several workers have been spawned. It's onlu reproducible in that I have a payload that will trigger it 100% of the time.

Thank you for the explanation for the IndexTransform. It validates the approach of clustering in space before doing the lookups.

I'll continue work on a minimal example tomorrow, e.g. pickling the inputs to the function in question.

**Comment by jbms** [comment]
Thanks, I'm working on reproducing as well.  Can you also confirm which version you are using?

**Comment by perlman** [comment]
I have a minimal example that breaks, but it needs local access to the data (does not work on a new, empty, array). I'll work on creating a minimal zarr now -- unless there is an http driver I am unaware of?

tensorstore==0.1.8

**Comment by perlman** [comment]
I doubt it's a coincidence: 28 is the directory being accessed:
`openat(AT_FDCWD, "/data/fields/flywire_v1/field.zarr/s2/194/99/28/0", O_RDONLY|O_CLOEXEC) = 3`

(I was using strace as a quick way to figure out files to bundle, but the code works with my new tiny `test.zarr`.)

**Comment by perlman** [comment]
I have an example _with_ zarr [here](https://spine.janelia.org/files/eric/ts_bug.tar.gz).

This is reproducible on my Mac as well:
`ValueError: In index array map for output dimension 0: Index 0 is outside valid range [28928, 29056)`

**Comment by jbms** [comment]
Thanks very much --- I can reproduce from your example.  Hopefully I can get to the bottom of it quickly now.

**Comment by jbms** [comment]
I have a fix for this bug, hopefully can push it out later today.
