### ISSUE TITLE
s3 support?

### ISSUE THREAD

**Issue by jingpengw** [google/tensorstore#46]
It seems that tensorstore does not support AWS S3, but only for GCS. Is there any plan to support it?

**Comment by jbms** [comment]
Currently, read-only access to S3 is possible through the `http` kvstore driver if no authentication is required.

A PR to add S3 support would certainly be welcome.  The actual operations should be quite straightforward to implement, similar to the `gcs` driver.  The most complicated part would be handling authentication.

**Comment by jingpengw** [comment]
thank you! 

the `http` kvstore driver is good enough for me.

**Comment by tchaton** [comment]
Any updates ?

**Comment by jbms** [comment]
Yes, I was thinking of using the REST API directly.  Ultimately the computation of the aws signature only requires a small amount of code, and this would allow tensorstore to have full control over the API usage, and ensure all operations are implemented fully asynchronously.  However, using the AWS C++ SDK for S3 (which I believe internally accesses the REST API via libcurl) could also be an option.  It would probably require less "development" effort, but may require more effort to integrate the AWS SDK into our build system.  I think that the AWS SDK can also be used with third-party implementations like `minio` and `ceph`.  It appears that `TransferManager` is a higher-level API on top of the low-level S3 API provided by the AWS SDK; I think it would probably be better to use the lower-level API rather than `TransferManager`.

**Comment by jbms** [comment]
If you are interested in adding S3 support, it would certainly be a much-appreciated contribution and we'd be happy to provide guidance on the tensorstore codebase.

**Comment by sjperkins** [comment]
> Yes, I was thinking of using the REST API directly. Ultimately the computation of the aws signature only requires a small amount of code, and this would allow tensorstore to have full control over the API usage, and ensure all operations are implemented fully asynchronously. However, using the AWS C++ SDK for S3 (which I believe internally accesses the REST API via libcurl) could also be an option. It would probably require less "development" effort, but may require more effort to integrate the AWS SDK into our build system. I think that the AWS SDK can also be used with third-party implementations like `minio` and `ceph`. It appears that `TransferManager` is a higher-level API on top of the low-level S3 API provided by the AWS SDK; I think it would probably be better to use the lower-level API rather than `TransferManager`.

I made a PUT REST API call [example](https://gist.github.com/sjperkins/15d3d196387cff8b6dc0dcca7f756fe8) where the AWS signature is calculated in Python -- easier to debug and to get an idea of what needs doing. I feel comfortable with the basics involved and it seems doable with the base tensorstore API.

Regarding the AWS C++ SDK, grafting the `tensorflow/io` [bazel](https://github.com/tensorflow/io/blob/master/third_party/aws-sdk-cpp.BUILD) files onto the tensorstore build system seems to work, but hopefully this won't be necessary.

> If you are interested in adding S3 support, it would certainly be a much-appreciated contribution and we'd be happy to provide guidance on the tensorstore codebase.

Yes, I'd like to have a go at this. I'll take another look at the C++ codebase and write up a basic implementation plan and some questions about it. For e.g.: HMAC-SHA256 support,, INI file parsing support for AWS credentials+config
