### ISSUE TITLE
How to consume this library via CMake?

### ISSUE THREAD

**Issue by dzenanz** [google/tensorstore#55]
Building the library via CMake works. This is good - we don't need to know bazel. But the build process does not produce even an `install` target, much less a `tensorstore-config.cmake` file.

The main point of CMakeifying the library is to enable it to be used via CMake, preferably with `find_package(tensorstore)` and `target_link_libraries(myLibrary tensorstore::all_drivers)` (or something similar). A usage example is [Qt](https://doc.qt.io/qt-5/cmake-get-started.html). Somebody wrote a relatively short [article](https://www.foonathan.net/2016/03/cmake-install/) about how to accomplish this.

If we have to discover the include directories, library files, and transitive dependencies, it does not really matter whether the library was compiled using CMake, bazel, autotools, or a totally custom bash script.

**Comment by jbms** [comment]
The recommended method for using this library is through FetchContent as described here:

https://google.github.io/tensorstore/installation.html#cmake-integration

That way, projects using TensorStore don't need to require their users to manually install it separately.

Potentially we could add an install target, but it would then be necessary to also "install" all of the dependencies, and I think we may run into some difficulties there.  Perhaps "install" would only be supported if all of the dependencies are provided as system/installed dependencies, rather than provided via FetchContent.

**Comment by dzenanz** [comment]
`install` target is not that important. But having `tensorstore-config.cmake` would allow multiple projects to use the same `tensorstore` build. The `FetchContent` approach requires each using project (library or executable) to have its own build.
