### ISSUE TITLE
Segfault when using PyTorch Dataloader with multiple workers

### ISSUE THREAD

**Issue by harpone** [google/tensorstore#61]
I wrote a pytorch Dataset class with TensorStore, which has a `__getitem__` method something like this:

```
def __getitem__(self, index):
        data_slice = self.data[index:index + 1].read().result() 
```

where `self.data = ts.open(config).result()` is a TensorStore dataset instance (GCS driver). This works fine.

Then I'm using the PyTorch Dataloader like this:

```
dataloader = td.DataLoader(dataset,
                           batch_size=16,
                           num_workers=num_workers)
```

where `num_workers` determines the number of python subprocesses launched, which will each download and process the data before collating all the data into a single tensor.

Everything works fine when `num_workers = 0`, but if `num_workers > 0`, I get a segfault in one of the worker processes.

I suspect it's the async `.read().result()` in the getitem... is TensorStore using multithreading under the hood which interferes with the Dataloader multiprocessing somehow? Can I turn it off somehow?

Or am I supposed to load all the data "lazily" and only call .return() after I have all the data retrieved and loaded? That would be a bit problematic since I would still need multiprocessing to handle any data preprocessing before packing it into a tensor and sending to GPU...

Is it possible at all to use TensorStore with a PyTorch Dataloader in the multiple workers context?

**Comment by jbms** [comment]
TensorStore relies on multithreading and that cannot be avoided.

Unfortunately multithreading is inherently incompatible with `fork`, which is used by default by the Python multiprocessing module on Linux.  I am not certain that your particular issue is related to that, though, because usually it manifests as a deadlock rather than segfault.  If you set multiprocessing to use the `spawn` method that would avoid the issue with multithreading, if indeed that is the problem.

Alternatively, if you ensure that tensorstore is not used prior to calling fork that would also avoid the problem.

If multithreading is not in fact the issue, then if you can provide a minimal reproducer of the crash, we might be able to help debug.

**Comment by harpone** [comment]
OK thanks, I'll try the spawn method!

Probably would be difficult to not use tensorstore before the fork since the Dataloader needs the tensorstore defined...

I'll try to get a minimal repro if the spawn method doesn't work and will post it here.

**Comment by harpone** [comment]
OK wow using `multiprocessing_context='spawn'` in the Dataloader does work (although need to wrap script in `if __name__ == '__main__':`). Seems a bit flaky and I wonder how this would work in a multi-node distributed training process... but OK good enough for now! Thanks!

Would it be possible to set the number of threads to 1 or something in TensorStore?

**Comment by harpone** [comment]
Just in case someone bumps into this problem later: I was able to use the 'fork' `multiprocessing_context` by moving the tensorstore open to the Dataset `__getitem__` method like this:

```
if self.data is None:  # Initialize TensorStore here after subprocesses forked to avoid hangs
            self.data = ts.open(self.config_read).result()
```
