### ISSUE TITLE
Infer kvstore driver automatically from a path

### ISSUE THREAD

**Issue by shoyer** [google/tensorstore#83]
To open a TensorStore from a path, you currently need to write something like:
```python
tensorstore.open({'driver': 'zarr', 'kvstore': {'driver': 'gcs', 'path': path}})
```

The file driver can usually be inferred from the path (e.g., does it start with `gs://` or not). Thus it would be nice to be able to write something simpler like:
```python
tensorstore.open({'driver': 'zarr', 'kvstore': {'path': path}})
```

Zarr-Python supports this sort of thing via fsspec.

**Comment by jbms** [comment]
This is kind of already supported:

'kvstore': 'file://...'

or 

'kvstore': 'gs://...'

We don't, however, interpret a plain string without a URI prefix as 'file://...', because there are some differences between URIs and local file paths, such as that URIs use percent encoding for characters outside the basic allowed set, while local file paths do not use any escaping, that would introduce some potential confusion and ambiguity.
