### ISSUE TITLE
windows build failing in riegeli::EstimatedAllocatedSize

### ISSUE THREAD

**Issue by toloudis** [google/tensorstore#93]
Just wondering if anyone is seeing this build error on Windows using VS 2019 build tools (C++ via cmake).  (Linux and MacOS seem to build ok):
```
324>D:\src\aics\agave\build\_deps\riegeli-src\riegeli/base/estimated_allocated_size.h(27,10): error C2672: 'riegeli::RoundUp': no matching overloaded function found
324>D:\src\aics\agave\build\_deps\riegeli-src\riegeli/base/estimated_allocated_size.h(27,10): error C2783: 'T riegeli::RoundUp(T)': could not deduce template argument for '__formal'
324>D:\src\aics\agave\build\_deps\riegeli-src\riegeli/base/arithmetic.h(315): message : see declaration of 'riegeli::RoundUp'
```
These errors are coming up when compiling the only source file in my codebase that uses tensorstore. It's hard for me to tell if it's my code or not so thought I'd see if anyone else has seen this error.  I got the same error in 0.1.32 and 0.1.35 but it only recently started happening.  One change I've made is upgrading Qt 5.15 to 6.5 but this particular source file is not including anything from Qt

**Comment by jbms** [comment]
What is the precise version of MSVC that you are using?

Also can you provide the full error message, or is what you pasted above all that it outputs?

**Comment by toloudis** [comment]
I am building the generated .sln file in the VS 2022 17.5.3 IDE, but the projects are using the VS 2019 tools with version 16.11.25 installed.
And yes the three lines I cited are the only errors reported for the file being compiled.  There's nothing else.  I'll try to isolate which tensorstore calls cause it by commenting things out ,and report what I find here.

**Comment by toloudis** [comment]
#include "tensorstore/open.h" is the include that leads to the errors.

**Comment by jbms** [comment]
We test with msvc-14.29.30037 and msvc-14.35.32215.  I can't find a recent enough version number chart that shows which MSVC version exactly is in those Visual Studio versions you listed (see https://blog.knatten.org/2022/08/26/microsoft-c-versions-explained/) but I think 16.11.25 is slightly newer than msvc-14.29.30037.  Perhaps there is a regression.

**Comment by toloudis** [comment]
I think my version is  14.35.32216.1  (link.exe appears to show the corresponding msvc version)

**Comment by toloudis** [comment]
also, I believe github-actions windows-2019 config is also seeing a newer version (and my build breakage happens there too)

**Comment by laramiel** [comment]
@QrczakMK Did you see this?

What happens if you patch [riegeli/base/estimate_allocated_size.h](https://github.com/google/riegeli/blob/master/riegeli/base/estimated_allocated_size.h) and change the RoundUp` call to something like this:

```
  return RoundUp<2 * sizeof(void*), size_t>(
      UnsignedMax<size_t, size_t>(requested_size, 4 * sizeof(void*)));
```

**Comment by QrczakMK** [comment]
This is definitely excessive. `UnsignedMax()` is used in a lot of places without explicit template arguments. `RoundUp()` too should be able to deduce the template argument. I see no reason why the current code would be incorrect.

It works in MSVC 19: https://godbolt.org/z/sa58571P5. Godbolt does not have older MSVC versions so I cannot experiment with them.

Why does this not work in MSVC 17? Is this a compiler bug? What is its nature, i.e. in which circumstances it cannot deduce the template argument?

**Comment by QrczakMK** [comment]
`__formal` in the error message suggests that the compiler has a problem with the `std::enable_if_t` parameter, because it is unnamed — I guess this is the name placeholder.

The template parameter involves `absl::has_single_bit`, which is defined as `std::has_single_bit` `#if defined(__cpp_lib_int_pow2) && __cpp_lib_int_pow2 >= 202002L`, otherwise it is defined explicitly.

https://en.cppreference.com/w/cpp/numeric/has_single_bit

Maybe MSVC provides `has_single_bit()` but it is not `constexpr`, which makes it unusable in `std::enable_if_t`?

In that case the bug is in MSVC; Abseil might work around this by using an explicit definition for buggy versions in MSVC; and Riegeli might work around this (before it can depend on a fixed Abseil version) by writing `alignment != 0 && (alignment & (alignment - 1)) == 0` instead of `absl::has_single_bit(alignment)` in the definition of `RoundUp()`.

**Comment by QrczakMK** [comment]
https://devblogs.microsoft.com/cppblog/bit-in-visual-studio-2019-version-16-8-preview-2/ claims that these functions are `constexpr` in MSVC 16.8, so I am not sure what is the real bug.

**Comment by jbms** [comment]
To be clear, tensorstore builds successfully with:

MSVC 14.29.30037
MSVC 14.35.32215

And apparently fails with

MSVC 14.29.30148 (though I have not yet actually tested with that MSVC version myself)

Occasionally it turns out that updates to MSVC report real errors that were missed by every other compiler, but in this case it is almost surely a new bug introduced in the new build of MSVC 14.29.

I have found lots of subtle bugs in MSVC related to template metaprogramming.  Sometimes something will work in isolation but will trigger a bug when combined with something else in the same translation unit --- those are a real pain to diagnose and find a workaround for.

**Comment by toloudis** [comment]
I confirmed that if I switch cmake generator to VS 2022 (msvc 14.35.32216.1) the same code compiles.  
We are using the older version to ensure compatibility with prebuilt dependencies that used the 14.29 compiler.

**Comment by jbms** [comment]
Hopefully we can fix this build issue, but I believe there is ABI compatibility between 14.29 and 14.35:

https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170

**Comment by toloudis** [comment]
I'll look into updating my project to vs2022 toolchain and see if I run into issues. 

Also fwiw, inline replacing `alignment != 0 && (alignment & (alignment - 1)) == 0` instead of `absl::has_single_bit(alignment)` in the RoundUp function did also make it compile.

**Comment by laramiel** [comment]
What's the _MSC_FULL_VER  for the failing compiler? Maybe we can get absl to increase the minimum version for msvc and `absl::has_single_bit` aliasing to `std::has_single_bit`.

https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170
https://docs.microsoft.com/en-us/visualstudio/releases/2019/history

**Comment by toloudis** [comment]
I'm pretty sure this was 16.11.24.  
Back in April when I had this issue, I worked around by updating my codebase to use more current compiler versions.  This is no longer an issue for me.
